# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgbXjXHsNrxyHzHQ7bZWw0cM1BazwUt8
"""

import streamlit as st
import pandas as pd
import numpy as np
import os
from sklearn.ensemble import RandomForestRegressor

def create_mock_data(filename='customer_churn_mock.csv'):
    np.random.seed(42)
    n_samples = 1000
    data = {
        'CustomerID': range(1, n_samples + 1),
        'Age': np.random.randint(18, 70, n_samples),
        'Tenure_Months': np.random.randint(1, 72, n_samples),
        'Monthly_Charge': np.random.uniform(500, 3000, n_samples).round(2),
        'Support_Tickets': np.random.randint(0, 6, n_samples)
    }
    df = pd.DataFrame(data)

    churn_prob = (
        (df['Support_Tickets'] * 0.12) +
        (1 / (df['Tenure_Months'] + 1)) * 0.4 +
        (df['Monthly_Charge'] / 3000) * 0.1
    )
    df['Churn'] = (np.random.rand(n_samples) < churn_prob).astype(int)
    df.to_csv(filename, index=False)
    return df

@st.cache_data
def train_model():
  if not os.path.exists('customer_churn_mock.csv'):
    df = create_mock_data()
  else:
    df = pd.read_csv('customer_churn_mock.csv')

  X = df.drop('Churn', axis=1)
  y = df['Churn']

  model = RandomForestRegressor(n_estimators=100, random_state=42)
  model.fit(X, y)
  return model

model = train_model()

#การออกแบบส่วนแสดงผล (User Interface) ที่จะใช้บน Streamlit
st.set_page_config(page_title='Customer Churn Prediction', page_icon=':bar_chart:', layout='wide')

st.title(':bar_chart: Customer Churn Prediction')
st.markdown("Application สำหรับทีมการตลาดเพื่อ **ประเมินความเสี่ยง** และ **จัดแคมเปญรักษาลูกค้า** เชิงรุก")
st.divider()

#การออกแบบส่วนแสดงผลแถบด้านข้าง (Sidebar) ที่จะใช้บน Streamlit สำหรับกรอกข้อมูลนำเข้า
st.sidebar.header("📝 กรอกข้อมูลนำเข้า")

age = st.sidebar.slider("อายุ (ปี)", 18, 70, 35)
tenure = st.sidebar.slider("ระยะเวลาที่ใช้บริการ (เดือน)", 1, 72, 6)
charge = st.sidebar.number_input("ค่าบริการต่อเดือน (บาท)", 500.00, 3000.00, 1500.00)
tickets = st.sidebar.selectbox("จำนวนครั้งที่ติดต่อฝ่าย Support (Suppot Ticket)", [0, 1, 2, 3, 4, 5])

#การทำนายผล
input_data = pd.DataFrame({
    'Age': [age],
    'Tenure_Months': [tenure],
    'Monthly_Charge': [charge],
    'Support_Tickets': [tickets]
})

prediction = model.predict(input_data)[0]
probability = model.predict_proba(input_data)[0][1]

#การแสดงผลของการทำนายผล
st.subheader("💡 ผลการวิเคราะห์และข้อเสนอแนะทางธุรกิจ")

if prediction == 1:
  st.error(f"⚠️ มีความเสี่ยงสูงที่ลูกค้ารายนี้มีโอกาสยกเลิกบริการ ({probability:.1%})")

  st.markdown("ACTION PLAN")
  st.info("""
  * **Retention Offer:** ส่ง SMS มอบคูปองส่วนลด 20% สำหรับรอบบิลถัดไป
  * **Proactive Service:** ให้ทีม Customer Success โทรสอบถามปัญหาการใช้งานโดยด่วน
  * **Expected ROI:** ค่าใช้จ่ายในการโทร+ส่วนลด คุ้มค่ากว่าการหาลูกค้าใหม่
  """)
else:
  st.error(f"✅ มีความเสี่ยงน้อยโดยที่ลูกค้ารายนี้มีแนวโน้มใช้งานต่อ(โดยมีความเสี่ยงเพียง{probability:.1%})")

  st.markdown("ACTION PLAN")
  st.info("""
  * **Relationship Building:** ส่งอีเมลขอบคุณสำหรับการใช้งานอย่างต่อเนื่อง
  * **Cross-sell Opportunity:** เสนอแพ็กเกจเสริม (Add-on) ที่เข้ากับพฤติกรรมการใช้งาน
  """)

